# Generated by Django 4.2 on 2023-12-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindetails',
            name='distributor_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logindetails',
            name='self_distributor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
