# Generated by Django 4.2 on 2023-12-22 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0004_logindetails_company_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindetails',
            name='company_id',
        ),
    ]
