# Generated by Django 4.2 on 2023-12-22 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0005_remove_logindetails_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.IntegerField(default=0, null=True)),
                ('price_list', models.IntegerField(default=0, null=True)),
                ('stock_adjustment', models.IntegerField(default=0, null=True)),
                ('godown', models.IntegerField(default=0, null=True)),
                ('cash_in_hand', models.IntegerField(default=0, null=True)),
                ('offline_banking', models.IntegerField(default=0, null=True)),
                ('upi', models.IntegerField(default=0, null=True)),
                ('bank_holders', models.IntegerField(default=0, null=True)),
                ('cheque', models.IntegerField(default=0, null=True)),
                ('reconciliation', models.IntegerField(default=0, null=True)),
                ('loan_account', models.IntegerField(default=0, null=True)),
                ('customers', models.IntegerField(default=0, null=True)),
                ('invoice', models.IntegerField(default=0, null=True)),
                ('estimate', models.IntegerField(default=0, null=True)),
                ('sales_order', models.IntegerField(default=0, null=True)),
                ('recurring_invoice', models.IntegerField(default=0, null=True)),
                ('retainer_invoice', models.IntegerField(default=0, null=True)),
                ('credit_note', models.IntegerField(default=0, null=True)),
                ('payment_received', models.IntegerField(default=0, null=True)),
                ('delivery_challan', models.IntegerField(default=0, null=True)),
                ('vendors', models.IntegerField(default=0, null=True)),
                ('bills', models.IntegerField(default=0, null=True)),
                ('recurring_bills', models.IntegerField(default=0, null=True)),
                ('vendor_credit', models.IntegerField(default=0, null=True)),
                ('purchase_order', models.IntegerField(default=0, null=True)),
                ('expenses', models.IntegerField(default=0, null=True)),
                ('recurring_expenses', models.IntegerField(default=0, null=True)),
                ('payment_made', models.IntegerField(default=0, null=True)),
                ('projects', models.IntegerField(default=0, null=True)),
                ('chart_of_accounts', models.IntegerField(default=0, null=True)),
                ('manual_journal', models.IntegerField(default=0, null=True)),
                ('eway_bill', models.IntegerField(default=0, null=True)),
                ('employees', models.IntegerField(default=0, null=True)),
                ('employees_loan', models.IntegerField(default=0, null=True)),
                ('holiday', models.IntegerField(default=0, null=True)),
                ('attendance', models.IntegerField(default=0, null=True)),
                ('salary_details', models.IntegerField(default=0, null=True)),
                ('reports', models.IntegerField(default=0, null=True)),
                ('update_action', models.IntegerField(default=0, null=True)),
                ('status', models.CharField(default='New', max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
            ],
        ),
    ]
