# Generated by Django 4.2.6 on 2024-01-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=255)),
                ('Name', models.TextField(max_length=255)),
                ('unit', models.TextField(max_length=255)),
                ('hsn', models.IntegerField(blank=True, null=True)),
                ('tax', models.TextField(max_length=255, null=True)),
                ('intratax', models.IntegerField(blank=True, null=True)),
                ('intertax', models.IntegerField(blank=True, null=True)),
                ('s_price', models.IntegerField(blank=True, null=True)),
                ('s_account', models.TextField(max_length=255)),
                ('s_desc', models.TextField(max_length=255)),
                ('p_price', models.IntegerField(blank=True, null=True)),
                ('p_account', models.TextField(max_length=255)),
                ('p_desc', models.TextField(max_length=255)),
                ('minimum_stock', models.IntegerField(blank=True, null=True)),
                ('satus', models.TextField(default='active')),
                ('invacc', models.TextField(max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('opstock', models.IntegerField(blank=True, default=0, null=True)),
                ('oprate', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
