# Generated by Django 4.2.6 on 2024-01-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0006_remove_items_oprate_item_transaction_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='opening_stock_per_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
