# Generated by Django 4.2.6 on 2024-01-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0007_items_opening_stock_per_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart_of_Accounts',
        ),
    ]
