# Generated by Django 4.2.6 on 2024-01-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0009_chart_of_accounts_chart_of_accounts_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart_of_accounts',
            name='attachment',
        ),
        migrations.AddField(
            model_name='chart_of_accounts',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chart_of_accounts',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
