# Generated by Django 4.2.6 on 2024-01-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0014_chart_of_accounts_account_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart_of_accounts',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
