# Generated by Django 4.2.6 on 2024-01-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0016_alter_chart_of_accounts_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
