# Generated by Django 4.2.6 on 2024-01-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0017_items_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart_of_accounts',
            name='parent_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chart_of_accounts',
            name='sub_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
