# Generated by Django 4.2.6 on 2024-01-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0020_alter_items_minimum_stock_to_maintain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='minimum_stock_to_maintain',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
