# Generated by Django 4.2.6 on 2024-01-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0025_alter_items_minimum_stock_to_maintain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart_of_accounts',
            name='account_number',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
