# Generated by Django 4.2.6 on 2024-01-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0026_alter_chart_of_accounts_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='track_inventory',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
